#!/usr/bin/env python
"""Build the appendix qualitative-examples gallery for the report.

Reproducible: reads drive_sync/examples/manifest.json (produced by
export_examples.py and pulled from Drive), copies the chosen images into
technical_report/figures/examples/, and writes technical_report/examples_gallery.tex
(\\input by minivlm_doceval.tex). Two galleries:
  * diagnostic ladder: one representative (correct) example per dataset,
  * VWTQ failure gallery: Qwen's Wikipedia-table lookup failures.

Usage:  python scripts/make_examples_figure.py
"""
import json
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SRC = REPO / "drive_sync" / "examples"
DST = REPO / "technical_report" / "figures" / "examples"
OUT = REPO / "technical_report" / "examples_gallery.tex"

LADDER = ["OCRBench", "DocVQA_VAL", "ChartQA_TEST", "InfoVQA_VAL", "TableVQABench"]
DISP = {"OCRBench": "OCRBench", "DocVQA_VAL": "DocVQA", "ChartQA_TEST": "ChartQA",
        "InfoVQA_VAL": "InfoVQA", "TableVQABench": "TableVQA"}


def clean_ans(s):
    """Unwrap stringified lists like "['CENTRE']" -> CENTRE for display."""
    import ast
    s = str(s).strip()
    if s.startswith("[") and s.endswith("]"):
        try:
            v = ast.literal_eval(s)
            if isinstance(v, (list, tuple)):
                return ", ".join(str(x) for x in v)
        except (ValueError, SyntaxError):
            pass
    return s


def esc(s):
    s = str(s)
    repl = [("\\", r"\textbackslash{}"), ("&", r"\&"), ("%", r"\%"), ("$", r"\$"),
            ("#", r"\#"), ("_", r"\_"), ("{", r"\{"), ("}", r"\}"),
            ("~", r"\textasciitilde{}"), ("^", r"\textasciicircum{}")]
    for a, b in repl:
        s = s.replace(a, b)
    return s


def fmt(s, n):
    """Clean a list-wrapped answer, truncate raw, escape, then append a LaTeX ellipsis."""
    s = clean_ans(s)
    cut = len(s) > n
    return esc(s[:n - 1] if cut else s) + (r"\,\ldots" if cut else "")


def copy_img(e):
    shutil.copy(SRC / e["image"], DST / e["image"])
    return "examples/" + e["image"]


def card(e, height, header, correct):
    rel = copy_img(e)
    pred_color = "green!45!black" if correct else "red!75!black"
    lines = [
        r"\begin{minipage}[t]{0.48\textwidth}\centering\vspace{0pt}",
        rf"\includegraphics[width=\linewidth,height={height},keepaspectratio]{{{rel}}}\\[2pt]",
        r"\scriptsize\raggedright " + header,
        rf"\textit{{Q:}} {fmt(e['question'], 92)}\\",
        rf"\textcolor{{green!45!black}}{{\textbf{{Gold:}} {fmt(e['gold'], 38)}}}"
        rf"\quad\textcolor{{{pred_color}}}{{\textbf{{Qwen:}} {fmt(e['prediction'], 38)}}}",
        r"\end{minipage}",
    ]
    return "\n".join(lines)


def grid(cards):
    """Two cards per row, separated by \\hfill; rows by \\par\\medskip."""
    out = []
    for i in range(0, len(cards), 2):
        row = cards[i:i + 2]
        out.append("\n\\hfill\n".join(row))
        out.append(r"\par\medskip")
    return "\n".join(out)


def main():
    global SRC
    import argparse
    ap = argparse.ArgumentParser()
    ap.add_argument("--src", default=str(REPO / "drive_sync" / "examples"),
                    help="dir with the exported examples (manifest.json + PNGs); "
                         "default drive_sync/examples, or point at <OUT_DIR>/examples")
    args = ap.parse_args()
    SRC = Path(args.src)

    m = json.loads((SRC / "manifest.json").read_text())
    DST.mkdir(parents=True, exist_ok=True)

    rep = {}
    for e in m:
        if e["role"] == "representative" and e["dataset"] not in rep:
            rep[e["dataset"]] = e
    reps = [card(rep[d], "3.0cm", rf"\textbf{{{DISP[d]}.}} ", True) for d in LADDER if d in rep]
    fails = [e for e in m if e["role"] == "vwtq_failure"][:6]
    fail_cards = [card(e, "3.4cm", rf"\textbf{{{e['split'].replace('_', '-').upper()}}}\quad ", False)
                  for e in fails]

    tex = [
        r"% Auto-generated by scripts/make_examples_figure.py -- do not edit by hand.",
        r"\begin{figure}[p]\centering",
        grid(reps),
        r"\caption{Representative examples across the benchmark suite (the diagnostic"
        r" ladder), each with Qwen3.5-0.8B's (correct) answer. Colours: gold answer"
        r" (green), model answer (green when correct).}",
        r"\label{fig:examples-ladder}",
        r"\end{figure}",
        r"",
        r"\begin{figure}[p]\centering",
        grid(fail_cards),
        r"\caption{Failure gallery on Wikipedia-style visual tables (VWTQ/VWTQ-Syn),"
        r" the measured weak sub-skill. The errors are \emph{lookup} mistakes---"
        r" miscounting rows, returning an adjacent column/row, or emitting a cell value"
        r" of the wrong type---not failures to read the table. Gold (green) vs Qwen"
        r" (red).}",
        r"\label{fig:examples-vwtq}",
        r"\end{figure}",
        r"",
    ]
    OUT.write_text("\n".join(tex))
    print(f"[gallery] copied {len(reps) + len(fail_cards)} images -> {DST}")
    print(f"[gallery] wrote {OUT}")


if __name__ == "__main__":
    main()
    sys.exit(0)
